// Mocks generated by Mockito 5.0.13 from annotations
// in wanderer/test/home_controller_unit_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:wanderer/modules/home/models/location_data_model.dart' as _i4;
import 'package:wanderer/modules/home/repositories/location_fetch_repository.dart'
    as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [GetLocationListRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetLocationListRepository extends _i1.Mock
    implements _i2.GetLocationListRepository {
  MockGetLocationListRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.LocationDataModel>> fetchLocationList() =>
      (super.noSuchMethod(Invocation.method(#fetchLocationList, []),
              returnValue: Future<List<_i4.LocationDataModel>>.value(
                  <_i4.LocationDataModel>[]))
          as _i3.Future<List<_i4.LocationDataModel>>);
  @override
  String toString() => super.toString();
}
